apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: m318a4qde-go-gitops
  description: This is GitOps manifest for m318a4qde-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=m318a4qde-go
    backstage.io/kubernetes-id: m318a4qde-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: m318a4qde-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:m318a4qde-go
